# Jekyll Configuration File

# Site settings
title: My GitHub Pages Site
description: A simple GitHub Pages site using Jekyll.
url: https://your-username.github.io/your-repo-name
baseurl: "" # Optional: For a subfolder, use "/your-repo-name"

# Author information
author:
  name: Your Name
  email: your-email@example.com

# Theme settings
theme: jekyll-theme-minimal # Default theme (you can change this to any of the themes below)
plugins:
  - jekyll-feed # Optional: Plugin for generating feeds

# Build settings
markdown: kramdown # Markdown processor
highlighter: rouge # Syntax highlighter

# Exclude files and directories from the build
exclude:
  - README.md
  - .gitignore
  - .DS_Store

# Other settings
permalink: pretty # Set the permalink style (pretty, date, etc.)
sass:
  style: compressed # CSS output style (nested, expanded, compact, compressed)
