# ----
# Site

title: Hydra Template
url: "https://proud-alligator.cloudvent.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product marketing template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Hydra Template
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window# Jekyll Configuration File

# Site settings
title: My GitHub Pages Site
description: A simple GitHub Pages site using Jekyll.
url: https://your-username.github.io/your-repo-name
baseurl: "" # Optional: For a subfolder, use "/your-repo-name"

# Author information
author:
  name: Your Name
  email: your-email@example.com

# Theme settings
theme: jekyll-theme-minimal # Replace with your chosen theme
plugins:
  - jekyll-feed # Optional: Plugin for generating feeds

# Build settings
markdown: kramdown # Markdown processor
highlighter: rouge # Syntax highlighter

# Exclude files and directories from the build
exclude:
  - README.md
  - .gitignore
  - .DS_Store

# Other settings
permalink: pretty # Set the permalink style (pretty, date, etc.)
sass:
  style: compressed # CSS output style (nested, expanded, compact, compressed)
